version: "3.1"

services:
  elasticsearch:
    container_name: els
    build:
        context: ./elasticsearch
        dockerfile: Dockerfile
    image: vniu_elasticsearch
    ports:
      - 9200:80
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elasticnetwork

  kibana:
    container_name: kibana
    build:
      context: ./kibana
      dockerfile: Dockerfile
    image: vniu_kibana
    ports:
      - 5601:80
    depends_on:
      - elasticsearch
    # environment:
    #   - ELASTICSEARCH_URL=http://localhost:80
    networks:
      - elasticnetwork
networks:
  elasticnetwork:
    driver: bridge

volumes:
  elasticsearch-data:
